-- ====================================================================
-- SWARAM DATABASE SCRIPT: 01_create_tables.sql
-- Purpose: Defines the 15 core normalized tables for Swaram.
-- Compatible with Oracle Database 11g, 12c, 19c, 21c, 23c and SQL*Plus.
-- ====================================================================

SET ECHO OFF;
SET FEEDBACK OFF;
PROMPT Creating Swaram core tables...;

-- 1. USERS
CREATE TABLE USERS (
    USER_ID             NUMBER NOT NULL,
    USERNAME            VARCHAR2(50) NOT NULL,
    EMAIL               VARCHAR2(100) NOT NULL,
    PASSWORD_HASH       VARCHAR2(255) NOT NULL,
    ROLE                VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    ACCOUNT_STATUS      VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 2. MOODS
CREATE TABLE MOODS (
    MOOD_ID             NUMBER NOT NULL,
    MOOD_CODE           VARCHAR2(30) NOT NULL,
    MOOD_NAME           VARCHAR2(50) NOT NULL,
    DESCRIPTION         VARCHAR2(255) NOT NULL,
    BACKGROUND_PATH     VARCHAR2(255) NOT NULL,
    IS_ACTIVE           CHAR(1) DEFAULT 'Y' NOT NULL,
    DISPLAY_ORDER       NUMBER DEFAULT 1 NOT NULL,
    CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 3. USER_PREFERENCES
CREATE TABLE USER_PREFERENCES (
    PREFERENCE_ID       NUMBER NOT NULL,
    USER_ID             NUMBER NOT NULL,
    THEME               VARCHAR2(10) DEFAULT 'DARK' NOT NULL,
    DEFAULT_MOOD_ID     NUMBER,
    CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 4. ARTISTS
CREATE TABLE ARTISTS (
    ARTIST_ID           NUMBER NOT NULL,
    ARTIST_NAME         VARCHAR2(100) NOT NULL,
    COUNTRY             VARCHAR2(60),
    CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 5. ALBUMS
CREATE TABLE ALBUMS (
    ALBUM_ID            NUMBER NOT NULL,
    ALBUM_TITLE         VARCHAR2(150) NOT NULL,
    ARTIST_ID           NUMBER NOT NULL,
    RELEASE_YEAR        NUMBER(4),
    ARTWORK_PATH        VARCHAR2(255),
    CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 6. SONGS
CREATE TABLE SONGS (
    SONG_ID             NUMBER NOT NULL,
    TITLE               VARCHAR2(150) NOT NULL,
    ALBUM_ID            NUMBER,
    DURATION_SECONDS    NUMBER NOT NULL,
    RELEASE_YEAR        NUMBER(4),
    LANGUAGE            VARCHAR2(50) DEFAULT 'Instrumental',
    ARTWORK_PATH        VARCHAR2(255),
    IS_ACTIVE           CHAR(1) DEFAULT 'Y' NOT NULL,
    UPLOADED_BY         NUMBER,
    CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 7. SONG_ARTISTS (Junction: Song <-> Artist)
CREATE TABLE SONG_ARTISTS (
    SONG_ID             NUMBER NOT NULL,
    ARTIST_ID           NUMBER NOT NULL,
    ARTIST_ROLE         VARCHAR2(30) DEFAULT 'PRIMARY' NOT NULL
);

-- 8. SONG_SOURCES
CREATE TABLE SONG_SOURCES (
    SOURCE_ID           NUMBER NOT NULL,
    SONG_ID             NUMBER NOT NULL,
    SOURCE_TYPE         VARCHAR2(30) DEFAULT 'LOCAL_MP3' NOT NULL,
    SOURCE_REFERENCE    VARCHAR2(500) NOT NULL,
    IS_PRIMARY          CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 9. SONG_MOODS (Junction: Song <-> Mood)
CREATE TABLE SONG_MOODS (
    SONG_ID             NUMBER NOT NULL,
    MOOD_ID             NUMBER NOT NULL,
    RELEVANCE           NUMBER(3, 2) DEFAULT 1.00 NOT NULL
);

-- 10. PLAYLISTS (System-curated)
CREATE TABLE PLAYLISTS (
    PLAYLIST_ID         NUMBER NOT NULL,
    MOOD_ID             NUMBER NOT NULL,
    PLAYLIST_NAME       VARCHAR2(100) NOT NULL,
    DESCRIPTION         VARCHAR2(255),
    COVER_PATH          VARCHAR2(255),
    IS_SYSTEM           CHAR(1) DEFAULT 'Y' NOT NULL,
    IS_ACTIVE           CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 11. PLAYLIST_SONGS (Junction: Playlist <-> Song)
CREATE TABLE PLAYLIST_SONGS (
    PLAYLIST_ID         NUMBER NOT NULL,
    SONG_ID             NUMBER NOT NULL,
    TRACK_NUMBER        NUMBER NOT NULL
);

-- 12. USER_PLAYLISTS (User-created)
CREATE TABLE USER_PLAYLISTS (
    USER_PLAYLIST_ID    NUMBER NOT NULL,
    USER_ID             NUMBER NOT NULL,
    PLAYLIST_NAME       VARCHAR2(100) NOT NULL,
    DESCRIPTION         VARCHAR2(255),
    COVER_PATH          VARCHAR2(255),
    IS_PUBLIC           CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 13. USER_PLAYLIST_SONGS (Junction: User Playlist <-> Song)
CREATE TABLE USER_PLAYLIST_SONGS (
    USER_PLAYLIST_ID    NUMBER NOT NULL,
    SONG_ID             NUMBER NOT NULL,
    TRACK_NUMBER        NUMBER NOT NULL,
    ADDED_AT            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 14. FAVORITES (Junction: User <-> Song)
CREATE TABLE FAVORITES (
    USER_ID             NUMBER NOT NULL,
    SONG_ID             NUMBER NOT NULL,
    ADDED_AT            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 15. LISTENING_HISTORY
CREATE TABLE LISTENING_HISTORY (
    HISTORY_ID          NUMBER NOT NULL,
    USER_ID             NUMBER,
    SONG_ID             NUMBER NOT NULL,
    MOOD_ID             NUMBER,
    STARTED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETED           CHAR(1) DEFAULT 'N' NOT NULL,
    LISTENED_SECONDS    NUMBER DEFAULT 0 NOT NULL
);

PROMPT Swaram tables created successfully.;
SET FEEDBACK ON;
