-- ====================================================================
-- SWARAM DATABASE SCRIPT: 03_create_constraints.sql
-- Purpose: Adds Primary Keys, Unique, Foreign Key, and Check constraints.
-- Compatible with Oracle Database 11g, 12c, 19c, 21c, 23c and SQL*Plus.
-- ====================================================================

SET ECHO OFF;
SET FEEDBACK OFF;
PROMPT Adding constraints to Swaram tables...;

-- ====================================================================
-- 1. PRIMARY KEYS
-- ====================================================================

ALTER TABLE USERS
    ADD CONSTRAINT PK_USERS PRIMARY KEY (USER_ID);

ALTER TABLE MOODS
    ADD CONSTRAINT PK_MOODS PRIMARY KEY (MOOD_ID);

ALTER TABLE USER_PREFERENCES
    ADD CONSTRAINT PK_USER_PREFERENCES PRIMARY KEY (PREFERENCE_ID);

ALTER TABLE ARTISTS
    ADD CONSTRAINT PK_ARTISTS PRIMARY KEY (ARTIST_ID);

ALTER TABLE ALBUMS
    ADD CONSTRAINT PK_ALBUMS PRIMARY KEY (ALBUM_ID);

ALTER TABLE SONGS
    ADD CONSTRAINT PK_SONGS PRIMARY KEY (SONG_ID);

ALTER TABLE SONG_ARTISTS
    ADD CONSTRAINT PK_SONG_ARTISTS PRIMARY KEY (SONG_ID, ARTIST_ID);

ALTER TABLE SONG_SOURCES
    ADD CONSTRAINT PK_SONG_SOURCES PRIMARY KEY (SOURCE_ID);

ALTER TABLE SONG_MOODS
    ADD CONSTRAINT PK_SONG_MOODS PRIMARY KEY (SONG_ID, MOOD_ID);

ALTER TABLE PLAYLISTS
    ADD CONSTRAINT PK_PLAYLISTS PRIMARY KEY (PLAYLIST_ID);

ALTER TABLE PLAYLIST_SONGS
    ADD CONSTRAINT PK_PLAYLIST_SONGS PRIMARY KEY (PLAYLIST_ID, SONG_ID);

ALTER TABLE USER_PLAYLISTS
    ADD CONSTRAINT PK_USER_PLAYLISTS PRIMARY KEY (USER_PLAYLIST_ID);

ALTER TABLE USER_PLAYLIST_SONGS
    ADD CONSTRAINT PK_USER_PLAYLIST_SONGS PRIMARY KEY (USER_PLAYLIST_ID, SONG_ID);

ALTER TABLE FAVORITES
    ADD CONSTRAINT PK_FAVORITES PRIMARY KEY (USER_ID, SONG_ID);

ALTER TABLE LISTENING_HISTORY
    ADD CONSTRAINT PK_LISTENING_HISTORY PRIMARY KEY (HISTORY_ID);

-- ====================================================================
-- 2. UNIQUE CONSTRAINTS
-- ====================================================================

ALTER TABLE USERS
    ADD CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME)
    ADD CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL);

ALTER TABLE MOODS
    ADD CONSTRAINT UQ_MOODS_CODE UNIQUE (MOOD_CODE)
    ADD CONSTRAINT UQ_MOODS_NAME UNIQUE (MOOD_NAME);

ALTER TABLE USER_PREFERENCES
    ADD CONSTRAINT UQ_USER_PREF_USER_ID UNIQUE (USER_ID);

ALTER TABLE ARTISTS
    ADD CONSTRAINT UQ_ARTISTS_NAME UNIQUE (ARTIST_NAME);

ALTER TABLE ALBUMS
    ADD CONSTRAINT UQ_ALBUMS_TITLE_ARTIST UNIQUE (ALBUM_TITLE, ARTIST_ID);

ALTER TABLE PLAYLISTS
    ADD CONSTRAINT UQ_PLAYLISTS_MOOD_NAME UNIQUE (MOOD_ID, PLAYLIST_NAME);

ALTER TABLE PLAYLIST_SONGS
    ADD CONSTRAINT UQ_PLAYLIST_SONGS_TRACK UNIQUE (PLAYLIST_ID, TRACK_NUMBER);

ALTER TABLE USER_PLAYLIST_SONGS
    ADD CONSTRAINT UQ_USER_PL_SONGS_TRACK UNIQUE (USER_PLAYLIST_ID, TRACK_NUMBER);

-- ====================================================================
-- 3. CHECK CONSTRAINTS
-- ====================================================================

ALTER TABLE USERS
    ADD CONSTRAINT CK_USERS_ROLE CHECK (ROLE IN ('USER', 'ADMIN'))
    ADD CONSTRAINT CK_USERS_STATUS CHECK (ACCOUNT_STATUS IN ('ACTIVE', 'INACTIVE', 'BLOCKED'));

ALTER TABLE MOODS
    ADD CONSTRAINT CK_MOODS_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
    ADD CONSTRAINT CK_MOODS_DISPLAY_ORDER CHECK (DISPLAY_ORDER > 0);

ALTER TABLE USER_PREFERENCES
    ADD CONSTRAINT CK_USER_PREF_THEME CHECK (THEME IN ('DARK', 'LIGHT'));

ALTER TABLE ALBUMS
    ADD CONSTRAINT CK_ALBUMS_YEAR CHECK (RELEASE_YEAR IS NULL OR (RELEASE_YEAR >= 1900 AND RELEASE_YEAR <= 2100));

ALTER TABLE SONGS
    ADD CONSTRAINT CK_SONGS_DURATION CHECK (DURATION_SECONDS >= 0)
    ADD CONSTRAINT CK_SONGS_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
    ADD CONSTRAINT CK_SONGS_YEAR CHECK (RELEASE_YEAR IS NULL OR (RELEASE_YEAR >= 1900 AND RELEASE_YEAR <= 2100));

ALTER TABLE SONG_ARTISTS
    ADD CONSTRAINT CK_SONG_ARTISTS_ROLE CHECK (ARTIST_ROLE IN ('PRIMARY', 'FEATURED', 'COMPOSER', 'OTHER'));

ALTER TABLE SONG_SOURCES
    ADD CONSTRAINT CK_SONG_SOURCES_TYPE CHECK (SOURCE_TYPE IN ('LOCAL_MP3', 'YOUTUBE', 'SPOTIFY', 'DIRECT_AUDIO'))
    ADD CONSTRAINT CK_SONG_SOURCES_PRIMARY CHECK (IS_PRIMARY IN ('Y', 'N'));

ALTER TABLE SONG_MOODS
    ADD CONSTRAINT CK_SONG_MOODS_RELEVANCE CHECK (RELEVANCE >= 0.00 AND RELEVANCE <= 1.00);

ALTER TABLE PLAYLISTS
    ADD CONSTRAINT CK_PLAYLISTS_SYSTEM CHECK (IS_SYSTEM IN ('Y', 'N'))
    ADD CONSTRAINT CK_PLAYLISTS_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'));

ALTER TABLE PLAYLIST_SONGS
    ADD CONSTRAINT CK_PLAYLIST_SONGS_TRACK CHECK (TRACK_NUMBER > 0);

ALTER TABLE USER_PLAYLISTS
    ADD CONSTRAINT CK_USER_PLAYLISTS_PUBLIC CHECK (IS_PUBLIC IN ('Y', 'N'));

ALTER TABLE USER_PLAYLIST_SONGS
    ADD CONSTRAINT CK_USER_PL_SONGS_TRACK CHECK (TRACK_NUMBER > 0);

ALTER TABLE LISTENING_HISTORY
    ADD CONSTRAINT CK_HISTORY_COMPLETED CHECK (COMPLETED IN ('Y', 'N'))
    ADD CONSTRAINT CK_HISTORY_LISTENED_SEC CHECK (LISTENED_SECONDS >= 0);

-- ====================================================================
-- 4. FOREIGN KEY CONSTRAINTS
-- ====================================================================

-- USER_PREFERENCES
ALTER TABLE USER_PREFERENCES
    ADD CONSTRAINT FK_USER_PREF_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID) ON DELETE CASCADE
    ADD CONSTRAINT FK_USER_PREF_MOOD FOREIGN KEY (DEFAULT_MOOD_ID)
        REFERENCES MOODS (MOOD_ID) ON DELETE SET NULL;

-- ALBUMS
ALTER TABLE ALBUMS
    ADD CONSTRAINT FK_ALBUMS_ARTIST FOREIGN KEY (ARTIST_ID)
        REFERENCES ARTISTS (ARTIST_ID) ON DELETE CASCADE;

-- SONGS
ALTER TABLE SONGS
    ADD CONSTRAINT FK_SONGS_ALBUM FOREIGN KEY (ALBUM_ID)
        REFERENCES ALBUMS (ALBUM_ID) ON DELETE SET NULL
    ADD CONSTRAINT FK_SONGS_UPLOADER FOREIGN KEY (UPLOADED_BY)
        REFERENCES USERS (USER_ID) ON DELETE SET NULL;

-- SONG_ARTISTS
ALTER TABLE SONG_ARTISTS
    ADD CONSTRAINT FK_SONG_ARTISTS_SONG FOREIGN KEY (SONG_ID)
        REFERENCES SONGS (SONG_ID) ON DELETE CASCADE
    ADD CONSTRAINT FK_SONG_ARTISTS_ARTIST FOREIGN KEY (ARTIST_ID)
        REFERENCES ARTISTS (ARTIST_ID) ON DELETE CASCADE;

-- SONG_SOURCES
ALTER TABLE SONG_SOURCES
    ADD CONSTRAINT FK_SONG_SOURCES_SONG FOREIGN KEY (SONG_ID)
        REFERENCES SONGS (SONG_ID) ON DELETE CASCADE;

-- SONG_MOODS
ALTER TABLE SONG_MOODS
    ADD CONSTRAINT FK_SONG_MOODS_SONG FOREIGN KEY (SONG_ID)
        REFERENCES SONGS (SONG_ID) ON DELETE CASCADE
    ADD CONSTRAINT FK_SONG_MOODS_MOOD FOREIGN KEY (MOOD_ID)
        REFERENCES MOODS (MOOD_ID) ON DELETE CASCADE;

-- PLAYLISTS
ALTER TABLE PLAYLISTS
    ADD CONSTRAINT FK_PLAYLISTS_MOOD FOREIGN KEY (MOOD_ID)
        REFERENCES MOODS (MOOD_ID) ON DELETE CASCADE;

-- PLAYLIST_SONGS
ALTER TABLE PLAYLIST_SONGS
    ADD CONSTRAINT FK_PL_SONGS_PLAYLIST FOREIGN KEY (PLAYLIST_ID)
        REFERENCES PLAYLISTS (PLAYLIST_ID) ON DELETE CASCADE
    ADD CONSTRAINT FK_PL_SONGS_SONG FOREIGN KEY (SONG_ID)
        REFERENCES SONGS (SONG_ID) ON DELETE CASCADE;

-- USER_PLAYLISTS
ALTER TABLE USER_PLAYLISTS
    ADD CONSTRAINT FK_USER_PL_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID) ON DELETE CASCADE;

-- USER_PLAYLIST_SONGS
ALTER TABLE USER_PLAYLIST_SONGS
    ADD CONSTRAINT FK_USER_PL_SONGS_PLAYLIST FOREIGN KEY (USER_PLAYLIST_ID)
        REFERENCES USER_PLAYLISTS (USER_PLAYLIST_ID) ON DELETE CASCADE
    ADD CONSTRAINT FK_USER_PL_SONGS_SONG FOREIGN KEY (SONG_ID)
        REFERENCES SONGS (SONG_ID) ON DELETE CASCADE;

-- FAVORITES
ALTER TABLE FAVORITES
    ADD CONSTRAINT FK_FAVORITES_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID) ON DELETE CASCADE
    ADD CONSTRAINT FK_FAVORITES_SONG FOREIGN KEY (SONG_ID)
        REFERENCES SONGS (SONG_ID) ON DELETE CASCADE;

-- LISTENING_HISTORY
ALTER TABLE LISTENING_HISTORY
    ADD CONSTRAINT FK_HISTORY_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID) ON DELETE SET NULL
    ADD CONSTRAINT FK_HISTORY_SONG FOREIGN KEY (SONG_ID)
        REFERENCES SONGS (SONG_ID) ON DELETE CASCADE
    ADD CONSTRAINT FK_HISTORY_MOOD FOREIGN KEY (MOOD_ID)
        REFERENCES MOODS (MOOD_ID) ON DELETE SET NULL;

PROMPT Swaram constraints added successfully.;
SET FEEDBACK ON;
