-- ====================================================================
-- SWARAM DATABASE SCRIPT: 04_create_indexes.sql
-- Purpose: Creates performance indexes for foreign keys and common search predicates.
-- Compatible with Oracle Database 11g, 12c, 19c, 21c, 23c and SQL*Plus.
-- Note: Columns already backed by Unique/PK indexes are excluded to prevent redundancy.
-- ====================================================================

SET ECHO OFF;
SET FEEDBACK OFF;
PROMPT Creating Swaram performance indexes...;

-- 1. SONGS Indexes
CREATE INDEX IDX_SONGS_TITLE ON SONGS (TITLE);
CREATE INDEX IDX_SONGS_ALBUM_ID ON SONGS (ALBUM_ID);
CREATE INDEX IDX_SONGS_UPLOADED_BY ON SONGS (UPLOADED_BY);
CREATE INDEX IDX_SONGS_IS_ACTIVE ON SONGS (IS_ACTIVE);

-- 2. ALBUMS Indexes
CREATE INDEX IDX_ALBUMS_ARTIST_ID ON ALBUMS (ARTIST_ID);

-- 3. SONG_SOURCES Indexes
CREATE INDEX IDX_SONG_SOURCES_SONG_ID ON SONG_SOURCES (SONG_ID);
CREATE INDEX IDX_SONG_SOURCES_TYPE ON SONG_SOURCES (SOURCE_TYPE);

-- 4. SONG_ARTISTS Reverse Index (ARTIST_ID lookup)
CREATE INDEX IDX_SONG_ARTISTS_ARTIST_ID ON SONG_ARTISTS (ARTIST_ID);

-- 5. SONG_MOODS Reverse Index (MOOD_ID lookup)
CREATE INDEX IDX_SONG_MOODS_MOOD_ID ON SONG_MOODS (MOOD_ID);

-- 6. PLAYLISTS Indexes
CREATE INDEX IDX_PLAYLISTS_MOOD_ID ON PLAYLISTS (MOOD_ID);
CREATE INDEX IDX_PLAYLISTS_IS_ACTIVE ON PLAYLISTS (IS_ACTIVE);

-- 7. PLAYLIST_SONGS Reverse Index (SONG_ID lookup)
CREATE INDEX IDX_PL_SONGS_SONG_ID ON PLAYLIST_SONGS (SONG_ID);

-- 8. USER_PLAYLISTS Indexes
CREATE INDEX IDX_USER_PL_USER_ID ON USER_PLAYLISTS (USER_ID);

-- 9. USER_PLAYLIST_SONGS Reverse Index (SONG_ID lookup)
CREATE INDEX IDX_USER_PL_SONGS_SONG_ID ON USER_PLAYLIST_SONGS (SONG_ID);

-- 10. FAVORITES Reverse Index (SONG_ID lookup)
CREATE INDEX IDX_FAVORITES_SONG_ID ON FAVORITES (SONG_ID);

-- 11. LISTENING_HISTORY Indexes
CREATE INDEX IDX_HISTORY_USER_ID ON LISTENING_HISTORY (USER_ID);
CREATE INDEX IDX_HISTORY_SONG_ID ON LISTENING_HISTORY (SONG_ID);
CREATE INDEX IDX_HISTORY_MOOD_ID ON LISTENING_HISTORY (MOOD_ID);
CREATE INDEX IDX_HISTORY_STARTED_AT ON LISTENING_HISTORY (STARTED_AT);

-- 12. USER_PREFERENCES
CREATE INDEX IDX_USER_PREF_MOOD_ID ON USER_PREFERENCES (DEFAULT_MOOD_ID);

PROMPT Swaram performance indexes created successfully.;
SET FEEDBACK ON;
