-- ====================================================================
-- SWARAM DATABASE SCRIPT: 05_create_triggers.sql
-- Purpose: Creates triggers for sequence auto-population and UPDATED_AT maintenance.
-- Compatible with Oracle Database 11g, 12c, 19c, 21c, 23c and SQL*Plus.
-- ====================================================================

SET ECHO OFF;
SET FEEDBACK OFF;
PROMPT Creating Swaram triggers...;

-- ====================================================================
-- 1. PRIMARY KEY AUTO-POPULATION TRIGGERS (BEFORE INSERT)
-- ====================================================================

CREATE OR REPLACE TRIGGER TRG_USERS_BI
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
    IF :NEW.USER_ID IS NULL THEN
        SELECT SEQ_USERS.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
    END IF;
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_USER_PREF_BI
BEFORE INSERT ON USER_PREFERENCES
FOR EACH ROW
BEGIN
    IF :NEW.PREFERENCE_ID IS NULL THEN
        SELECT SEQ_USER_PREFERENCES.NEXTVAL INTO :NEW.PREFERENCE_ID FROM DUAL;
    END IF;
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_MOODS_BI
BEFORE INSERT ON MOODS
FOR EACH ROW
BEGIN
    IF :NEW.MOOD_ID IS NULL THEN
        SELECT SEQ_MOODS.NEXTVAL INTO :NEW.MOOD_ID FROM DUAL;
    END IF;
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_ARTISTS_BI
BEFORE INSERT ON ARTISTS
FOR EACH ROW
BEGIN
    IF :NEW.ARTIST_ID IS NULL THEN
        SELECT SEQ_ARTISTS.NEXTVAL INTO :NEW.ARTIST_ID FROM DUAL;
    END IF;
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ALBUMS_BI
BEFORE INSERT ON ALBUMS
FOR EACH ROW
BEGIN
    IF :NEW.ALBUM_ID IS NULL THEN
        SELECT SEQ_ALBUMS.NEXTVAL INTO :NEW.ALBUM_ID FROM DUAL;
    END IF;
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_SONGS_BI
BEFORE INSERT ON SONGS
FOR EACH ROW
BEGIN
    IF :NEW.SONG_ID IS NULL THEN
        SELECT SEQ_SONGS.NEXTVAL INTO :NEW.SONG_ID FROM DUAL;
    END IF;
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_SONG_SOURCES_BI
BEFORE INSERT ON SONG_SOURCES
FOR EACH ROW
BEGIN
    IF :NEW.SOURCE_ID IS NULL THEN
        SELECT SEQ_SONG_SOURCES.NEXTVAL INTO :NEW.SOURCE_ID FROM DUAL;
    END IF;
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PLAYLISTS_BI
BEFORE INSERT ON PLAYLISTS
FOR EACH ROW
BEGIN
    IF :NEW.PLAYLIST_ID IS NULL THEN
        SELECT SEQ_PLAYLISTS.NEXTVAL INTO :NEW.PLAYLIST_ID FROM DUAL;
    END IF;
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_USER_PLAYLISTS_BI
BEFORE INSERT ON USER_PLAYLISTS
FOR EACH ROW
BEGIN
    IF :NEW.USER_PLAYLIST_ID IS NULL THEN
        SELECT SEQ_USER_PLAYLISTS.NEXTVAL INTO :NEW.USER_PLAYLIST_ID FROM DUAL;
    END IF;
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_LISTENING_HISTORY_BI
BEFORE INSERT ON LISTENING_HISTORY
FOR EACH ROW
BEGIN
    IF :NEW.HISTORY_ID IS NULL THEN
        SELECT SEQ_LISTENING_HISTORY.NEXTVAL INTO :NEW.HISTORY_ID FROM DUAL;
    END IF;
    IF :NEW.STARTED_AT IS NULL THEN
        :NEW.STARTED_AT := SYSTIMESTAMP;
    END IF;
END;
/

-- ====================================================================
-- 2. AUDIT UPDATED_AT TRIGGERS (BEFORE UPDATE)
-- ====================================================================

CREATE OR REPLACE TRIGGER TRG_USERS_BU
BEFORE UPDATE ON USERS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_USER_PREF_BU
BEFORE UPDATE ON USER_PREFERENCES
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_MOODS_BU
BEFORE UPDATE ON MOODS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_SONGS_BU
BEFORE UPDATE ON SONGS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_PLAYLISTS_BU
BEFORE UPDATE ON PLAYLISTS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_USER_PLAYLISTS_BU
BEFORE UPDATE ON USER_PLAYLISTS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

PROMPT Swaram triggers created successfully.;
SET FEEDBACK ON;
